### ISSUE TITLE
pac-man-bot setup guide problems

### ISSUE THREAD

**Issue by ntrinite** [KSU-IEEE/pac-man-bot#7]
Error after running: python3 dependencies.py -a  

Runs fine until it throws and error after "INstalling python dependencies"
Error is:
INstalling python dependencies
Traceback (most recent call last):
  File "dependencies.py", line 90, in <module>
    cmd = 'pip install ' + python_list 
TypeError: must be str, not NoneType

I checked the .py file and I guess you're going to add this in later if you wrote this yourself?

Error after running: cmake .. -GNinja 

I ran the mkdir launch include src command before like you told me

Error is:
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:305 (message):
  catkin_package() include dir 'include' does not exist relative to
  '/home/ntrinite/IEEE/pac-man-bot/catkin_ws/src/statemachine'
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  catkin_ws/src/statemachine/CMakeLists.txt:71 (catkin_package)

-- Configuring incomplete, errors occurred!
See also "/home/ntrinite/IEEE/pac-man-bot/build/CMakeFiles/CMakeOutput.log".
See also "/home/ntrinite/IEEE/pac-man-bot/build/CMakeFiles/CMakeError.log".

can't test after this point because of the error

**Comment by trov4** [comment]
Updated submodules to have directories hard coded in (will need to remove the temp files at a later date, github will only commit directories if there are files in them, so I added temp.h and temp.launch to KSU-IEEE/statemachine and KSU-IEEE/ros-wrappers  

Also updated dependencies output to add "(ignore this)" add the end of that line. There aren't any python deps right now, so yeah you won't see anything download for that, I can see that being weird for new users.

@ntrinite Can you checkout the branch `7-pac-man-bot-setup-guide-problems` update the submodules with `git submodule update --init --recursive` and continue on from where you left off

**Comment by ntrinite** [comment]
cmake .. -GNinja worked
ninja worked
srcros: command not found

**Comment by trov4** [comment]
Alias in bashscript was not added to ~/.bashrc at all.......

**Comment by trov4** [comment]
✅ updated python script works 
✅ roslaunch works 

❌ bashscript was not ran at all on Noah's machine -- this is the last fix to make 

Update the readme to have an expected output for the roslaunch command

**Comment by trov4** [comment]
I couldn't figure out why the bashcript wasn't running on Noah's machine. 
   
So instead, I switched from calling a setup bashscript to a CMakeFunction, so there shouldn't be any problems because Noah's cmake command was able to run one of my other cmake functions before. 

I've asked @ntrinite to test it out on his machine again. Once it works I'll merge everything into main.
